-- Insert data for Company 1
INSERT INTO company (cin, company_name, roc, company_reg_number, sub_category, company_class, no_members, date_of_registration, email, listed_flag, last_agm_date, balance_sheet_date, registered_state, company_status, category, company_type, authorized_capital, paidup_capital, principal_business_activity, activity_code, registered_office_address, date, country, currency, year, month, day)
VALUES ('U98200UT2023PTC015565', 'TNT VENTURES PRIVATE LIMITED', 'RoC-Uttarakhand', 15565, 'Non-govt company', 'Private', 0, '2023-04-30', 'dushyantsethi.yardstick@gmail.com', 'Unlisted', '-', '-', 'UTTARAKHAND', 'ACTIVE', 'COMPANY LIMITED BY SHARES', 'Non-government company', 1500000, 100000, 'UNDIFFERENTIATED SERVICE-PRODUCING ACTIVITIES OF PRIVATE HOUSEHOLDS FOR OWN USE', 0, 'C/O DUSHYANT SETHI, SHOP OLD CHUNGI, GAIROLA NAGAR, HARIDWAR ROAD,,RISHIKESH, DEHRADUN, UTTARAKHAND, INDIA - 249201', '2023-04-30 00:00:00', 'INDIA', 'INR', 2023, 4, 30);

-- Insert data for Company 2
INSERT INTO company (cin, company_name, roc, company_reg_number, sub_category, company_class, no_members, date_of_registration, email, listed_flag, last_agm_date, balance_sheet_date, registered_state, company_status, category, company_type, authorized_capital, paidup_capital, principal_business_activity, activity_code, registered_office_address, date, country, currency, year, month, day)
VALUES ('U98200UT2023PTC015566', 'XYZ VENTURES PRIVATE LIMITED', 'RoC-Uttarakhand', 15566, 'Non-govt company', 'Private', 0, '2023-04-30', 'info@xyzventures.com', 'Unlisted', '-', '-', 'UTTARAKHAND', 'ACTIVE', 'COMPANY LIMITED BY SHARES', 'Non-government company', 1500000, 100000, 'Software Development', 0, 'C/O John Doe, 123 Main Street, City, State, Country - 123456', '2023-04-30 00:00:00', 'INDIA', 'INR', NULL, NULL, NULL);

-- Insert data for Company 3
INSERT INTO company (cin, company_name, roc, company_reg_number, sub_category, company_class, no_members, date_of_registration, email, listed_flag, last_agm_date, balance_sheet_date, registered_state, company_status, category, company_type, authorized_capital, paidup_capital, principal_business_activity, activity_code, registered_office_address, date, country, currency, year, month, day)
VALUES ('U98200UT2023PTC015567', 'ABC ENTERPRISES PRIVATE LIMITED', 'RoC-Uttarakhand', 15567, 'Non-govt company', 'Private', 0, '2023-04-30', 'contact@abcenterprises.com', 'Unlisted', '-', '-', 'UTTARAKHAND', 'ACTIVE', 'COMPANY LIMITED BY SHARES', 'Non-government company', 1500000, 100000, 'Marketing Services', 0, 'C/O Jane Smith, 456 Oak Avenue, Town, State, Country - 789012', '2023-04-30 00:00:00', 'INDIA', 'INR', NULL, NULL, NULL);
